## Importando o pandas e gerendo o dataframe


In [ ]:
!pip install scikit-learn

In [33]:
import pandas as pd
import numpy as np

# Criando um DataFrame com valores nulos
data = {
    'Nome': ['Ana', None, 'Carlos', 'Diana', 'Eduardo'],
    'Idade': [23, np.nan, 45, None, 33],
    'Cidade': ['São Paulo', 'Rio de Janeiro', None, 'Porto Alegre', 'Salvador']
}
df = pd.DataFrame(data)

In [2]:
df

Nome  Idade          Cidade
0      Ana   23.0       São Paulo
1     None    NaN  Rio de Janeiro
2   Carlos   45.0            None
3    Diana    NaN    Porto Alegre
4  Eduardo   33.0        Salvador

In [3]:
# drop de linhas com valores nulos(faltantes)
df_limpo = df.dropna()

# drop de colunas com valores nulos(faltantes)
df_limpo_colunas = df.dropna(axis = 1)




In [5]:
df_limpo_colunas

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [6]:
df.isna().sum()

Nome      1
Idade     2
Cidade    1
dtype: int64

Fazer no execel uma tabela contendo a nota de 3 alunos, Nome do aluno, e as notas em historia, matematica e Geografia não preecher as notas de dois alunos na disciplina de matematica

In [7]:
df_notas = pd.read_excel('dados/notas.xlsx')

In [8]:
df_notas

nome  Historia  Matematica  Geografia
0    Ana        10         8.0         10
1  Paulo         7         NaN          8
2  Roger         7         NaN          9

In [9]:
df_notas_corrigido = df_notas.fillna(0)

In [10]:
df_notas_corrigido

nome  Historia  Matematica  Geografia
0    Ana        10         8.0         10
1  Paulo         7         0.0          8
2  Roger         7         0.0          9

In [11]:
df_notas.isna().sum()

nome          0
Historia      0
Matematica    2
Geografia     0
dtype: int64

In [ ]:
df_preenchido = df_notas.fillna(0)

In [15]:
df_notas.bfill()

nome  Historia  Matematica  Geografia
0    Ana        10         8.0         10
1  Paulo         7         8.0          8
2  Roger         7         8.0          9

In [20]:
df_notas.loc[3] = {'nome':'Carlos','Historia':10, 'Matematica':10, 'Geografia':9}

In [22]:
df_notas.bfill()

nome  Historia  Matematica  Geografia
0     Ana        10         8.0         10
1   Paulo         7        10.0          8
2   Roger         7        10.0          9
3  Carlos        10        10.0          9

In [34]:
df['Idade'].fillna(df['Idade'].median(), inplace=True)

/tmp/ipykernel_2809/1473801709.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Idade'].fillna(df['Idade'].median(), inplace=True)


In [39]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import BayesianRidge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [40]:
data = {
    'Idade': [25, np.nan, 35, 40, 28, 30, np.nan, 22],
    'Altura': [175, 180, 165, np.nan, 170, 174, 179, 160],
    'Peso': [70, 80, 60, 75, np.nan, 70, 85, 55]
}
df = pd.DataFrame(data)

In [41]:
imp_bayesian = IterativeImputer(estimator=BayesianRidge())

In [42]:
df_bayesian = imp_bayesian.fit_transform(df)

In [43]:
df_bayesian

array([[ 25.        , 175.        ,  70.        ],
       [ 31.8132677 , 180.        ,  80.        ],
       [ 35.        , 165.        ,  60.        ],
       [ 40.        , 175.23107122,  75.        ],
       [ 28.        , 170.        ,  66.97367861],
       [ 30.        , 174.        ,  70.        ],
       [ 32.22081812, 179.        ,  85.        ],
       [ 22.        , 160.        ,  55.        ]])

In [45]:
# Usando Decision Tree
imp_decision_tree = IterativeImputer(estimator=DecisionTreeRegressor())
df_decision_tree = imp_decisiont_tree.fit_transform(df)
df_decision_tree

array([[ 25., 175.,  70.],
       [ 40., 180.,  80.],
       [ 35., 165.,  60.],
       [ 40., 174.,  75.],
       [ 28., 170.,  70.],
       [ 30., 174.,  70.],
       [ 40., 179.,  85.],
       [ 22., 160.,  55.]])

In [46]:
# Usando Randon Forest
imp_randon_forest = IterativeImputer(estimator=RandomForestRegressor())
df_randon_forest = imp_randon_forest.fit_transform(df)
df_randon_forest

/home/msus/.local/lib/python3.10/site-packages/sklearn/impute/_iterative.py:825: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(


array([[ 25.  , 175.  ,  70.  ],
       [ 35.86, 180.  ,  80.  ],
       [ 35.  , 165.  ,  60.  ],
       [ 40.  , 177.02,  75.  ],
       [ 28.  , 170.  ,  66.8 ],
       [ 30.  , 174.  ,  70.  ],
       [ 35.86, 179.  ,  85.  ],
       [ 22.  , 160.  ,  55.  ]])